// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BlazorRestaurant.DataAccess.Models
{
    [Index(nameof(ApplicationUserId), Name = "UI_ApplicationUserRole_ApplicationUserId", IsUnique = true)]
    public partial class ApplicationUserRole
    {
        [Key]
        public long ApplicationUserRoleId { get; set; }
        public long ApplicationUserId { get; set; }
        public short ApplicationRoleId { get; set; }

        [ForeignKey(nameof(ApplicationRoleId))]
        [InverseProperty("ApplicationUserRole")]
        public virtual ApplicationRole ApplicationRole { get; set; }
        [ForeignKey(nameof(ApplicationUserId))]
        [InverseProperty("ApplicationUserRole")]
        public virtual ApplicationUser ApplicationUser { get; set; }
    }
}