// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorRestaurant.DataAccess.Models
{
    public partial class ErrorLog
    {
        public long ErrorLogId { get; set; }
        public string Message { get; set; }
        public string StackTrace { get; set; }
        public string FullException { get; set; }
        public DateTimeOffset RowCreationDateTime { get; set; }
        public string RowCreationUser { get; set; }
        public string SourceApplication { get; set; }
        public string OriginatorIpaddress { get; set; }
    }
}