// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorRestaurant.DataAccess.Models
{
    public partial class ExternalRequestTracking
    {
        public long ExternalRequestTrackingId { get; set; }
        public string RequestContentHeaders { get; set; }
        public string RequestContentString { get; set; }
        public string RequestHeaders { get; set; }
        public string RequestMethod { get; set; }
        public string RequestUrl { get; set; }
        public string ResponseContentHeaders { get; set; }
        public string ResponseContentString { get; set; }
        public string ResponseReasonPhrase { get; set; }
        public int ResponseStatusCode { get; set; }
        public DateTimeOffset RowCreationDateTime { get; set; }
        public string RowCreationUser { get; set; }
        public string SourceApplication { get; set; }
        public string OriginatorIpaddress { get; set; }
    }
}