// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BlazorRestaurant.DataAccess.Models
{
    public partial class ExternalRequestTracking
    {
        [Key]
        public long ExternalRequestTrackingId { get; set; }
        public string RequestContentHeaders { get; set; }
        public string RequestContentString { get; set; }
        [Required]
        public string RequestHeaders { get; set; }
        [Required]
        [StringLength(50)]
        public string RequestMethod { get; set; }
        [Required]
        public string RequestUrl { get; set; }
        [Required]
        public string ResponseContentHeaders { get; set; }
        public string ResponseContentString { get; set; }
        public string ResponseReasonPhrase { get; set; }
        public int ResponseStatusCode { get; set; }
        public DateTimeOffset RowCreationDateTime { get; set; }
        [Required]
        [StringLength(256)]
        public string RowCreationUser { get; set; }
        [Required]
        [StringLength(250)]
        public string SourceApplication { get; set; }
        [Required]
        [Column("OriginatorIPAddress")]
        [StringLength(100)]
        public string OriginatorIpaddress { get; set; }
    }
}