// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BlazorRestaurant.DataAccess.Models
{
    [Table("ProductType", Schema = "products")]
    public partial class ProductType
    {
        public ProductType()
        {
            Product = new HashSet<Product>();
        }

        [Key]
        public short ProductTypeId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(50)]
        public string Description { get; set; }

        [InverseProperty("ProductType")]
        public virtual ICollection<Product> Product { get; set; }
    }
}