// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorRestaurant.DataAccess.Models
{
    public partial class SystemConfiguration
    {
        public int SystemConfigurationId { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    }
}