// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BlazorRestaurant.DataAccess.Models
{
    [Index(nameof(Name), Name = "UI_SystemConfiguration_Name", IsUnique = true)]
    public partial class SystemConfiguration
    {
        [Key]
        public int SystemConfigurationId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        public string Value { get; set; }
    }
}